/**
 * De identificatie van elke regel.
 *
 * Eén plek, zodat een regel-id in een bevinding, in een test, in het auditlog
 * en in de catalogus gegarandeerd hetzelfde is. Een typefout in een string
 * levert hier een compilatiefout op in plaats van een regel die stilletjes
 * nooit afgaat.
 */
export const RULE = {
  // ── Dagelijkse arbeidstijd en dienstlengte ─────────────────────────────────
  RP_MAX_WORK_PER_DUTY: "RP_MAX_WORK_PER_DUTY",
  RP_MAX_WORK_INCL_OVERTIME: "RP_MAX_WORK_INCL_OVERTIME",
  RP_MAX_WORK_START_0500_0600: "RP_MAX_WORK_START_0500_0600",
  RP_STATION_BREAK_ADJUSTMENT: "RP_STATION_BREAK_ADJUSTMENT",
  MIN_WORK_PER_DUTY: "MIN_WORK_PER_DUTY",
  RP_MAX_DUTY_DURATION: "RP_MAX_DUTY_DURATION",
  RP_MAX_DUTY_START_0400_0501: "RP_MAX_DUTY_START_0400_0501",
  RP_MAX_DUTY_START_0500_0600: "RP_MAX_DUTY_START_0500_0600",
  RP_MIN_DUTY_DURATION: "RP_MIN_DUTY_DURATION",

  // ── Dagelijkse rust ────────────────────────────────────────────────────────
  RP_DAILY_REST_PLANNED: "RP_DAILY_REST_PLANNED",
  DAILY_REST_REDUCED_NON_PLANNED: "DAILY_REST_REDUCED_NON_PLANNED",

  // ── Pauze en werkonderbreking ──────────────────────────────────────────────
  BREAK_OVER_5H30: "BREAK_OVER_5H30",
  BREAK_OVER_10H: "BREAK_OVER_10H",
  RP_LOCATION_WORK_INTERRUPTION: "RP_LOCATION_WORK_INTERRUPTION",

  // ── Wekelijkse arbeidstijd ─────────────────────────────────────────────────
  MAX_WEEKLY_HOURS: "MAX_WEEKLY_HOURS",
  AVG_WEEKLY_HOURS_4W: "AVG_WEEKLY_HOURS_4W",
  AVG_WEEKLY_HOURS_16W: "AVG_WEEKLY_HOURS_16W",
  AVG_WEEKLY_HOURS_16W_MANY_NIGHTS: "AVG_WEEKLY_HOURS_16W_MANY_NIGHTS",
  MANY_NIGHTS_THRESHOLD: "MANY_NIGHTS_THRESHOLD",

  // ── Wekelijkse rust en rustdagen ───────────────────────────────────────────
  WEEKLY_REST_36H_PER_7D: "WEEKLY_REST_36H_PER_7D",
  WEEKLY_REST_72H_PER_14D: "WEEKLY_REST_72H_PER_14D",
  WEEKLY_REST_SPLIT_MIN: "WEEKLY_REST_SPLIT_MIN",
  RC_SHORTENED_WEEKLY_REST_MIN: "RC_SHORTENED_WEEKLY_REST_MIN",
  RC_SHORTENED_WEEKLY_REST_INTERVAL_WEEKS: "RC_SHORTENED_WEEKLY_REST_INTERVAL_WEEKS",
  R_DAY_ATTACHED_MIN: "R_DAY_ATTACHED_MIN",
  R_DAY_DETACHED_MIN: "R_DAY_DETACHED_MIN",
  R_DAYS_PER_WEEK_AVG: "R_DAYS_PER_WEEK_AVG",
  RT_PREFERRED_WINDOW_WEEKS: "RT_PREFERRED_WINDOW_WEEKS",

  // ── Reeksen ────────────────────────────────────────────────────────────────
  MAX_CONSECUTIVE_SERVICES: "MAX_CONSECUTIVE_SERVICES",
  MAX_CONSECUTIVE_IN_NIGHT_SEQUENCE: "MAX_CONSECUTIVE_IN_NIGHT_SEQUENCE",

  // ── Nachtdiensten ──────────────────────────────────────────────────────────
  NIGHT_REST_AFTER_0200: "NIGHT_REST_AFTER_0200",
  NIGHT_SEQUENCE_RECOVERY: "NIGHT_SEQUENCE_RECOVERY",
  NIGHT_SEQUENCE_RECOVERY_THRESHOLD: "NIGHT_SEQUENCE_RECOVERY_THRESHOLD",
  MAX_NIGHT_SERVICES_16W: "MAX_NIGHT_SERVICES_16W",
  NIGHT_MAX_WORK: "NIGHT_MAX_WORK",
  NIGHT_MAX_WORK_INCL_OVERTIME: "NIGHT_MAX_WORK_INCL_OVERTIME",
  NIGHT_MAX_DUTY_DURATION: "NIGHT_MAX_DUTY_DURATION",
  RP_NIGHT_START_0400_0501_MAX_WORK: "RP_NIGHT_START_0400_0501_MAX_WORK",
  RP_NIGHT_START_0400_0501_MAX_DUTY: "RP_NIGHT_START_0400_0501_MAX_DUTY",
  RP_NIGHT_ACROSS_0230_MAX_WORK: "RP_NIGHT_ACROSS_0230_MAX_WORK",
  RP_NIGHT_ACROSS_0230_MAX_DUTY: "RP_NIGHT_ACROSS_0230_MAX_DUTY",
  RP_HARD_NIGHT_LATEST_END: "RP_HARD_NIGHT_LATEST_END",

  // ── Vroege starts en lange diensten ────────────────────────────────────────
  RP_MAX_EARLY_STARTS_0500_0600_PER_4W: "RP_MAX_EARLY_STARTS_0500_0600_PER_4W",
  RP_MAX_LONG_DUTIES_PER_YEAR: "RP_MAX_LONG_DUTIES_PER_YEAR",
  RP_LONG_DUTY_THRESHOLD: "RP_LONG_DUTY_THRESHOLD",

  // ── Individuele bescherming ────────────────────────────────────────────────
  AGE55_VERY_EARLY_EXEMPTION: "AGE55_VERY_EARLY_EXEMPTION",
  AGE50_HARD_NIGHT_EXEMPTION: "AGE50_HARD_NIGHT_EXEMPTION",
  INDIVIDUAL_SCHEDULING_RESTRICTION: "INDIVIDUAL_SCHEDULING_RESTRICTION",

  // ── Weekenden en zondagen ──────────────────────────────────────────────────
  RED_WEEKEND_MIN_REST: "RED_WEEKEND_MIN_REST",
  RED_WEEKEND_INTERVAL_WEEKS: "RED_WEEKEND_INTERVAL_WEEKS",
  MIN_FREE_SUNDAYS_52W: "MIN_FREE_SUNDAYS_52W",

  // ── Vrije dagen en feestdagen ──────────────────────────────────────────────
  HOLIDAY_ATTACHED_MIN: "HOLIDAY_ATTACHED_MIN",
  HOLIDAY_DETACHED_MIN: "HOLIDAY_DETACHED_MIN",
  RO_DVP_DETACHED_MIN: "RO_DVP_DETACHED_MIN",
  RO_DVP_COMBINED_MIN: "RO_DVP_COMBINED_MIN",
  PARTTIME_DASH_DAY_MIN: "PARTTIME_DASH_DAY_MIN",
  WTV_DAY_LATEST_START: "WTV_DAY_LATEST_START",
  WTV_DAYS_PER_YEAR_36H: "WTV_DAYS_PER_YEAR_36H",
  WITHDRAWN_WTV_GRANT_WITHIN_DAYS: "WITHDRAWN_WTV_GRANT_WITHIN_DAYS",

  // ── Roosterstructuur ───────────────────────────────────────────────────────
  ROSTER_ANCHOR_LOCKED: "ROSTER_ANCHOR_LOCKED",
  RESERVE_BASE_WITHOUT_DUTIES: "RESERVE_BASE_WITHOUT_DUTIES",

  // ── Kwalificaties en profiel ───────────────────────────────────────────────
  QUALIFICATIONS_REQUIRED: "QUALIFICATIONS_REQUIRED",
  ROSTER_PROFILE_BOUNDS: "ROSTER_PROFILE_BOUNDS",
  DEPOT_MATCH: "DEPOT_MATCH",
  DAY_AVAILABLE: "DAY_AVAILABLE",

  // ── Regionale en lokale kaders ─────────────────────────────────────────────
  REGIO_WEST_WEEKEND_TARGET: "REGIO_WEST_WEEKEND_TARGET",
  DORDRECHT_ROSTER_LINE_DIVISOR: "DORDRECHT_ROSTER_LINE_DIVISOR",
  REGIO_WEST_WTV_INTERVAL_WEEKS: "REGIO_WEST_WTV_INTERVAL_WEEKS",
  NEW_DRIVER_PROTECTION_YEARS: "NEW_DRIVER_PROTECTION_YEARS",
  PLAN_ROSTER_OVERFLOW_LIMIT: "PLAN_ROSTER_OVERFLOW_LIMIT",
  MIX_PROFILE_SPECIAL_RULES: "MIX_PROFILE_SPECIAL_RULES",
} as const;

export type RuleId = (typeof RULE)[keyof typeof RULE];
